version:0.0
os:linux
files:
  - source: /
    destination: /opt/odoo/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 500
  AfterInstall: 
    - location: scripts/after_install.sh
      timeout: 500
      runas: root
